document.writeln("<div class=\"header-content\">");
document.writeln("  <div class=\"header-header\">");
document.writeln("    <a href=\"#\" class=\"header-logo-content\"><img src=\"/appstore-man/images/logo.png\" class=\"logo\" alt=\"京东商城开发者\" height=\"60\" width=\"275\"></a>");
document.writeln("    <div class=\"header-login-bar\">");
document.writeln("      <ul class=\"header-pass-info\">");
document.writeln("        <li><a href=\"http://www.360buy.com\" target=\"_blank\">京东商城</a></li>");
document.writeln("        <li>|</li>");
document.writeln("        <li><a href=\"#\">登录</a></li>");
document.writeln("        <li>|</li>");
document.writeln("        <li><a href=\"http://218.240.59.197:8081/index.action\">注册</a></li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("  <div class=\"header-nav-wrapper\">");
document.writeln("    <div class=\"header-nav_l fl\"></div>");
document.writeln("    <div class=\"header-nav fl\">");
document.writeln("      <ul class=\"header-tabs\">");
document.writeln("        <li id=\"nav-home\" class=\"header-tabs-item\"><a href=\"http://218.240.59.197:8081/index.action\" class=\"header-tabs-btn\">首　页</a></li>");
document.writeln("        <li id=\"nav-app\" class=\"header-tabs-item \"><a href=\"app.html\" class=\"header-tabs-btn\">应用发布中心</a></li>");
document.writeln("        <li id=\"nav-statistics\" class=\"header-tabs-item \"><a href=\"down_num.html\" class=\"header-tabs-btn\">数据中心</a></li>");
document.writeln("      </ul>");
document.writeln("      <div class=\"header-nav-search fr hide\">");
document.writeln("      	<input id=\"search-keyword\" class=\"search-text\" type=\"text\" onblur=\"if(this.value==\'\'){this.value=\'全站搜索...\';}\" onfocus=\"if(this.value==\'全站搜索...\'){this.value=\'\';}\" value=\"全站搜索...\" name=\"q\">");
document.writeln("      	<input class=\"search-submit\" type=\"image\" alt=\"\" src=\"/appstore-man/images/search_btn.png\" >");
document.writeln("      </div>");
document.writeln("      <div class=\"header-nav-create fr\"><input id=\"input_create\" class=\"to-create open\" type=\"submit\" value=\"\" /></div>");
document.writeln("    </div>");
document.writeln("    <div class=\"header-nav_r fl\"></div>");
document.writeln("  </div>");
document.writeln("</div>");
