document.writeln("<div id=\"menu-box\">");
document.writeln("			<script type=\"text/javascript\" src=\"/appstore-man/js/menu.js\"></script>");
document.writeln("			<div class=\"box\">");
document.writeln("			  <h1><div class=\"title_1\"><span class=\"menu1\"></span></div></h1>");
document.writeln("			  <ul class=\"list\">");
document.writeln("              	<li><div class=\"ico_1 fl\"></div><a id=\"menu_1\" href=\"app.html\">全部应用</a></li>");
document.writeln("                <li><div class=\"ico_2 fl\"></div><a id=\"menu_2\" href=\"app.html\">移动游戏</a></li>");
document.writeln("                <li><div class=\"ico_3 fl\"></div><a id=\"menu_3\" href=\"app.html\">移动软件</a></li>");
document.writeln("                <li><div class=\"ico_4 fl\"></div><a id=\"menu_4\" href=\"app.html\">移动应用</a></li>");
document.writeln("			  </ul>");
document.writeln("			</div>");
document.writeln("			<div class=\"box\">");
document.writeln("			  <h2><div class=\"title_2\"><span class=\"menu1\"></span></div></h2>");
document.writeln("			  <ul class=\"list\">");
document.writeln("              	<li><div class=\"ico_5 fl\"></div><a id=\"menu_5\" href=\"personal_info.html\">个人信息</a></li>");
document.writeln("                <li><div class=\"ico_6 fl\"></div><a id=\"menu_6\" href=\"company_info.html\">公司信息</a></li>");
document.writeln("                <li><div class=\"ico_7 fl\"></div><a id=\"menu_7\" href=\"pay_app_info.html\">付费应用合同信息</a></li>");
document.writeln("			  </ul>");
document.writeln("			</div>");
document.writeln("            <div class=\"box\">");
document.writeln("			  <h3><div class=\"title_3\"><span class=\"menu1\"></span></div></h3>");
document.writeln("			  <ul class=\"list\">");
document.writeln("              	<li><div class=\"ico_8 fl\"></div><a id=\"menu_8\" href=\"modify_pass.html\">修改密码</a></li>");
document.writeln("                <li><div class=\"ico_9 fl\"></div><a id=\"menu_9\" href=\"bind_tel.html\">绑定手机</a></li>");
document.writeln("                <li><div class=\"ico_10 fl\"></div><a id=\"menu_10\" href=\"#\">更新提醒</a></li>");
document.writeln("			  </ul>");
document.writeln("			</div>");
document.writeln("        </div>");
